language: php

sudo: false

git:
  quiet: true
  depth: false

branches:
  only:
  - master
  - develop
  - /^release/.*$/

php:
- 7.0

cache:
  directories:
  - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_script:
- composer install --no-interaction --prefer-source --dev

script:
- vendor/bin/codecept run
- vendor/bin/phpcs --standard=phpcs.xml
- find {src, app, test} -name "*.php" ! -path '*/NonPHP7.php' -print0 | xargs -0 -n1 -P8 php -l

after_success:
- php vendor/bin/coveralls
