language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: nightly
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files

before_script:
- composer self-update
- composer install --prefer-source

script:
- vendor/bin/codecept run



notifications:
  email:
    recipients:
    - a.cacopardo@redspher.com
    on_success: always
    on_failure: always