language: php

php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- nightly


matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7.0
  - php: nightly
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files

before_script:
- composer self-update
- composer install --prefer-source


script:
- vendor/bin/codecept run



notifications:
  on_success: never
  on_failure: always
  email: a.cacopardo@redspher.com
  c'est la merde
