language: php
php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- nightly

branches:
  only:
  - master
  - develop
  - release

before_script:
- composer self-update

install:
- composer install --no-interaction

cache:
  directories:
  - $HOME/.composer/cache

script:
- vendor/bin/codecept run

notifications:
  email:
    on_success: always
    on_failure: always
