<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJS5UIWi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJS5UIWi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJS5UIWi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJS5UIWi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJS5UIWi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JS5UIWi',
    'container.build_id' => 'e962e0b5',
    'container.build_time' => 1552211152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJS5UIWi');
